services:
  db:
    image: postgres:17
    container_name: travel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: travel_tourism_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: travel_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: travel_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
      DJANGO_SECRET_KEY: "your_secret_key_here"
      DATABASE_ENGINE: django.db.backends.postgresql
      DATABASE_NAME: travel_tourism_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: travel_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
      - ./media:/media
    depends_on:
      - web

volumes:
  postgres_data:
